# Generated by Django 4.2.8 on 2023-12-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_account_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pin',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
