# Generated by Django 4.2.8 on 2023-12-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_transactions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='receiver',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='sender',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
